// Isolated Vite + fake hub: never sends repair prompts to the running fleet.
// Run: node test/recovery.visual.mjs
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm, mkdir, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createServer } from 'vite';
import { chromium } from 'playwright';

const fixture = await realpath(await mkdtemp(join(tmpdir(), 'orca-recovery-')));
const shots = resolve('test/shots/recovery');
let server, browser;
try {
  await writeFile(join(fixture, 'index.html'), '<html><head><meta charset="utf-8"><script src="/recovery.js"></script></head><body><script type="module" src="/broken.ts"></script></body></html>');
  await writeFile(join(fixture, 'broken.ts'), 'export const broken: string = `shader // `age` comment`;');
  await writeFile(join(fixture, 'healthy.html'), '<html><head><meta charset="utf-8"><script src="/recovery.js"></script></head><body>Healthy console</body></html>');
  server = await createServer({ configFile: false, root: fixture, publicDir: resolve('public'), logLevel: 'silent', server: { host: '127.0.0.1', port: 0 } });
  await server.listen();
  const origin = `http://127.0.0.1:${server.httpServer.address().port}`;
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('console', (m) => { if (m.type() === 'error') console.log('Browser:', m.text()); });
  page.on('pageerror', (e) => console.log('Page:', e.message));
  let connection;
  const frames = [];
  await page.routeWebSocket('**/ws/console', (ws) => {
    connection = ws;
    ws.onMessage((raw) => {
      const frame = JSON.parse(raw);
      frames.push(frame);
      if (frame.t === 'hello') ws.send(JSON.stringify({ t: 'world', state: { ceo: { messages: [] } } }));
    });
  });
  await page.goto(origin + '/healthy.html');
  assert.equal(await page.locator('orca-recovery').count(), 0);
  assert.equal(frames.length, 0, 'healthy app creates no extra hub connection');
  await page.goto(origin + '/?k=test-access-token');
  const panel = page.locator('orca-recovery');
  await panel.getByRole('button', { name: 'Send to CAPCOM' }).waitFor();
  await page.waitForFunction(() => document.querySelector('orca-recovery')?.shadowRoot.querySelector('[role=status]').textContent.includes('HUB CONNECTED'));
  await page.locator('vite-error-overlay').waitFor({ state: 'attached' });
  await panel.locator('pre').filter({ hasText: 'broken.ts' }).waitFor({ state: 'attached' });
  assert.equal(frames[0].token, 'test-access-token');
  assert.equal(new URL(page.url()).searchParams.has('k'), false);
  assert.equal(frames.filter((f) => f.t === 'ceo:say').length, 0, 'error alone never sends a repair request');
  await panel.getByLabel('Message CAPCOM', { exact: true }).fill('Please fix the compile error.');
  await panel.getByRole('button', { name: 'Send to CAPCOM' }).click();
  await page.waitForTimeout(50);
  const request = frames.find((f) => f.t === 'ceo:say');
  assert.match(request.text, /Please fix the compile error/);
  assert.match(request.text, /broken.ts/);
  assert.equal(await panel.getByRole('button', { name: 'Send to CAPCOM' }).isDisabled(), true);
  connection.send(JSON.stringify({ t: 'ack', cmdId: request.id, ok: false, detail: 'No CAPCOM connected. Your message was saved.' }));
  await panel.getByRole('status').filter({ hasText: 'No CAPCOM connected' }).waitFor();
  assert.equal(await panel.locator('textarea').inputValue(), 'Please fix the compile error.');
  await panel.getByRole('button', { name: 'Send to CAPCOM' }).click();
  await page.waitForTimeout(50);
  const second = frames.filter((f) => f.t === 'ceo:say').at(-1);
  connection.send(JSON.stringify({ t: 'ack', cmdId: second.id, ok: true }));
  connection.send(JSON.stringify({ t: 'ceo:message', message: { id: 'reply', role: 'ceo', text: 'Inspecting broken.ts. <img src=x onerror=alert(1)>', actions: [] } }));
  connection.send(JSON.stringify({ t: 'ceo:delta', id: 'reply', text: '\nThe repair is ready for review.' }));
  await panel.getByRole('log').filter({ hasText: 'ready for review' }).waitFor();
  assert.equal(await panel.locator('textarea').inputValue(), '');
  assert.equal(await panel.locator('img').count(), 0, 'CAPCOM content is rendered as text');
  await mkdir(shots, { recursive: true });
  await page.screenshot({ path: join(shots, 'desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  const bounds = await panel.boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y >= 0);
  await page.screenshot({ path: join(shots, 'mobile.png') });
  await panel.getByRole('button', { name: 'Minimize' }).click();
  assert.equal(await panel.locator('textarea').isVisible(), false);
  await panel.getByRole('button', { name: 'Open', exact: true }).click();
  await panel.locator('textarea').fill('Keep this draft.');
  await panel.getByRole('button', { name: 'Send to CAPCOM' }).click();
  connection.close({ code: 1011, reason: 'hub stopped' });
  await panel.getByRole('status').filter({ hasText: 'Delivery unconfirmed' }).waitFor();
  assert.equal(await panel.locator('textarea').inputValue(), 'Keep this draft.');
  await page.goto(origin + '/recovery.html');
  await panel.getByRole('status').filter({ hasText: 'HUB CONNECTED' }).waitFor();
  assert.equal(await panel.locator('textarea').inputValue(), 'Keep this draft.');
  assert.match(await panel.locator('pre').textContent(), /broken.ts/);
  connection.close({ code: 4001, reason: 'unauthorized' });
  await panel.getByRole('status').filter({ hasText: 'CONNECTION REJECTED' }).waitFor();
  assert.equal(await panel.getByRole('button', { name: 'Send to CAPCOM' }).isDisabled(), true);
  await page.goto(origin + '/healthy.html');
  await page.evaluate(() => window.dispatchEvent(new ErrorEvent('error', { message: 'Runtime failure', filename: 'main.js', lineno: 12 })));
  await panel.getByRole('status').filter({ hasText: 'HUB CONNECTED' }).waitFor();
  assert.match(await panel.locator('pre').textContent(), /Runtime failure/);
  let uploads = 0, uploadFails = true;
  await page.route('**/api/recovery-images', async (route) => {
    uploads++;
    assert.equal(route.request().headers()['authorization'], 'Bearer test-access-token');
    assert.equal(route.request().headers()['content-type'], 'image/png');
    await route.fulfill({ status: uploadFails ? 500 : 201, contentType: 'application/json', body: JSON.stringify(uploadFails ? { error: 'Disk unavailable' } : { path: '/hub/recovery-images/screenshot.png' }) });
  });
  await panel.locator('textarea').fill('');
  await panel.evaluate((host) => {
    const dt = new DataTransfer();
    dt.items.add(new File([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aMioAAAAASUVORK5CYII='), c => c.charCodeAt(0))], 'screenshot.png', { type: 'image/png' }));
    host.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: dt }));
  });
  assert.equal(await panel.locator('#attachments img').count(), 1);
  assert.equal(uploads, 0, 'dropping an image does not upload or send it');
  const beforeUpload = frames.filter(f => f.t === 'ceo:say').length;
  await panel.getByRole('button', { name: 'Send to CAPCOM' }).click();
  await panel.getByRole('status').filter({ hasText: 'Disk unavailable' }).waitFor();
  assert.equal(frames.filter(f => f.t === 'ceo:say').length, beforeUpload);
  assert.equal(await panel.locator('#attachments img').count(), 1, 'failed upload preserves the image');
  uploadFails = false;
  await panel.getByRole('button', { name: 'Send to CAPCOM' }).click();
  await panel.getByRole('status').filter({ hasText: 'SENDING' }).waitFor();
  await page.waitForTimeout(50);
  const imageRequest = frames.filter(f => f.t === 'ceo:say').at(-1);
  assert.match(imageRequest.text, /\/hub\/recovery-images\/screenshot.png/);
  await page.screenshot({ path: join(shots, 'mobile-images.png') });
  connection.send(JSON.stringify({ t: 'ack', cmdId: imageRequest.id, ok: true }));
  await panel.getByRole('status').filter({ hasText: 'DELIVERED' }).waitFor();
  assert.equal(await panel.locator('#attachments img').count(), 0);
  await panel.locator('#images').setInputFiles({ name: 'bad.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') });
  await panel.getByRole('status').filter({ hasText: 'use PNG' }).waitFor();
  assert.equal(await panel.locator('#attachments img').count(), 0);
  console.log('Image attachments passed: drop, preview, deferred authenticated upload, failed upload retention, image-only message, path delivery, cleanup, unsupported format.');
  console.log('Recovery passed: actual Vite compile failure, healthy boot, runtime error, authentication, explicit send, failure/success receipts, replies, safe text, disconnect, draft persistence, standalone page, desktop/mobile.');
} finally {
  await browser?.close();
  await server?.close();
  await rm(fixture, { recursive: true, force: true });
}
